# Generated by Django 2.2.12 on 2020-08-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0011_queryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype_table',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='userProfile'),
        ),
    ]
