# Generated by Django 2.2.12 on 2020-08-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0013_patientbookappointment_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookappointment',
            name='date',
            field=models.CharField(default=0.000455000455000455, max_length=100),
            preserve_default=False,
        ),
    ]
