# Generated by Django 2.2.12 on 2020-08-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0015_auto_20200815_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbookappointment',
            name='date',
        ),
    ]
