# Generated by Django 2.2.12 on 2020-08-15 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0016_remove_patientbookappointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookappointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 8, 43, 41, 564405, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
