# Generated by Django 2.2.12 on 2020-08-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0017_patientbookappointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookappointment',
            name='massage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
