# Generated by Django 2.2.12 on 2020-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0019_auto_20200815_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbookappointment',
            name='date',
            field=models.DateField(default='2020YY.01M.08/15/20D'),
        ),
    ]
