# Generated by Django 2.2.12 on 2020-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0020_auto_20200815_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbookappointment',
            name='date',
            field=models.DateField(default='08/15/20D.54M.2020YYY'),
        ),
    ]
