# Generated by Django 2.2.12 on 2020-08-15 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0022_auto_20200815_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookappointment',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 8, 15, 10, 46, 7, 463235, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
