# Generated by Django 2.2.12 on 2020-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0025_auto_20200815_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('about', models.CharField(max_length=500, null=True)),
                ('clinicInfo', models.CharField(max_length=100, null=True)),
                ('clinicAddress', models.CharField(max_length=100, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('service', models.CharField(max_length=200, null=True)),
                ('specialization', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
