# Generated by Django 2.2.12 on 2020-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0026_doctor_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_detail',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='doctorProfile'),
        ),
    ]
