# Generated by Django 2.2.12 on 2020-08-15 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amisapp1', '0027_doctor_detail_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_detail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
