# Generated by Django 2.2.12 on 2020-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0029_auto_20200815_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_detail',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_detail',
            name='pin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
