# Generated by Django 2.2.12 on 2020-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0031_auto_20200815_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype_table',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usertype_table',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usertype_table',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
