# Generated by Django 2.2.12 on 2020-08-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0033_dawa_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dawa_category',
        ),
    ]
