# Generated by Django 2.2.12 on 2020-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0036_auto_20200815_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='dawa_add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('descriptions', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
