# Generated by Django 2.2.12 on 2020-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0037_dawa_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawa_add_product',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
