# Generated by Django 2.2.12 on 2020-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0038_dawa_add_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawa_add_product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientbookappointment',
            name='date',
            field=models.DateField(default='16d.08m.20yyy'),
        ),
    ]
