# Generated by Django 2.2.12 on 2020-08-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0039_auto_20200816_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawa_add_product',
            name='image',
            field=models.ImageField(null=True, upload_to='productImage'),
        ),
    ]
