# Generated by Django 2.2.12 on 2020-08-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0041_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='medicin',
        ),
    ]
