# Generated by Django 2.2.12 on 2020-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0042_auto_20200816_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicin',
            name='shop_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
