# Generated by Django 2.2.12 on 2020-08-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0043_medicin_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicin',
            name='quantity',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
