# Generated by Django 2.2.12 on 2020-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0044_medicin_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicin',
            name='added_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
