# Generated by Django 2.2.12 on 2020-08-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0045_medicin_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbookappointment',
            name='accept',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientbookappointment',
            name='reject',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
