# Generated by Django 2.2.12 on 2020-08-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0047_auto_20200816_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbookappointment',
            name='accept',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
    ]
