# Generated by Django 2.2.12 on 2020-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0051_lab_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryform',
            name='user',
            field=models.CharField(default='amit', max_length=50),
            preserve_default=False,
        ),
    ]
