# Generated by Django 2.2.12 on 2020-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amisapp1', '0052_queryform_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('massage', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(null=True, upload_to='reportfile')),
            ],
        ),
    ]
